from django.urls import path
from . import views
from .views import (
    home, userdashboard, vendordashboard, upload_to_r2,
    get_print_requests, process_print_request, auto_print_documents, update_job_status,
    auth_receiver, sign_in, photoprint, vendor_register, vendor_pricing, vendor_info,
    vendor_login, vendor_register_api, mark_notification_read,
    enhance_passport_photo, forgot_password_page, forgot_password, verify_reset_code, reset_password,
    logout_view, get_vendor_coordinates, get_vendor_pricing, calculate_digital_print_pricing,
    calculate_gloss_print_pricing, calculate_photo_print_pricing, calculate_jumbo_print_pricing, calculate_passport_photo_pricing, calculate_a4_print_pricing, calculate_golden_emboss_pricing,
    get_vendor_print_jobs, list_r2_files, debug_vendor_registrations,
    update_vendor_service_availability, get_vendor_service_availability, 
    update_vendor_availability, update_vendor_profile, get_vendor_profile_image, test_profile_image_url, test_r2_url_generation, test_r2_simple, list_vendor_folder, logout,
    create_razorpay_order, verify_razorpay_payment, accept_print_job, mark_job_completed, hide_completed_job, debug_file_locations
)

urlpatterns = [
    path('', views.home, name='home'),
    path('upload/', views.upload_to_r2, name='upload_to_r2'),
    path('userdashboard/', views.userdashboard, name='userdashboard'),
    path('userdashboard-data/', views.userdashboard_data, name='userdashboard_data'),
    path('vendordashboard/', views.vendordashboard, name='vendordashboard'),
    path('get-print-requests/',
         views.get_print_requests,
         name='get-print-requests'),
    path('process_print/', process_print_request, name='process_print'),
    path('auto-print-documents/', views.auto_print_documents, name='auto-print-documents'),
    path('get-vendor-print-jobs/', views.get_vendor_print_jobs, name='get_vendor_print_jobs'),
    path('update-job-status/', update_job_status, name='update_job_status'),
    path('login/', sign_in, name='login'),
    path('logout/', logout, name='logout'),
    path('auth-receiver/', auth_receiver, name='auth_receiver'),
    path('photoprint/', photoprint, name='photoprint'),
    path('vendor-register/', views.vendor_register, name='vendor_register'),
    path('vendor-about/', views.vendor_about, name='vendor-about'),
    path('vendor-pricing/', vendor_pricing, name='vendor_pricing'),
    path('vendor-info/<str:vendor_id>/', vendor_info, name='vendor_info'),
    path('vendor-login/', vendor_login, name='vendor-login'),
    path('vendor-register-api/', vendor_register_api, name='vendor_register_api'),
    path('vendor-authenticate/', views.vendor_authenticate, name='vendor_authenticate'),
    path('get-available-shops/', views.get_available_shops, name='get_available_shops'),
    path('debug-vendor-registrations/', views.debug_vendor_registrations, name='debug_vendor_registrations'),
    path('get-vendor-pricing/', get_vendor_pricing, name='get_vendor_pricing'),
    #path('get-user-notifications/', get_user_notifications_api, name='get_user_notifications'),
    path('mark-notification-read/', mark_notification_read, name='mark_notification_read'),
    path('get-vendor-details/', views.get_vendor_details, name='get_vendor_details'),
    path('enhance-passport-photo/', enhance_passport_photo, name='enhance_passport_photo'),
    path('forgot-password/', forgot_password_page, name='forgot_password_page'),
    path('forgot-password-api/', forgot_password, name='forgot_password_api'),
    path('verify-reset-code/', verify_reset_code, name='verify_reset_code'),
    path('reset-password/', reset_password, name='reset_password'),
    path('logout/', logout_view, name='logout'),
    path('get-vendor-coordinates/', get_vendor_coordinates, name='get_vendor_coordinates'),
    path('calculate-digital-print-pricing/', calculate_digital_print_pricing, name='calculate_digital_print_pricing'),
    path('calculate-gloss-print-pricing/', calculate_gloss_print_pricing, name='calculate_gloss_print_pricing'),
    path('calculate-photo-print-pricing/', calculate_photo_print_pricing, name='calculate_photo_print_pricing'),
    path('calculate-jumbo-print-pricing/', calculate_jumbo_print_pricing, name='calculate_jumbo_print_pricing'),
    path('calculate-passport-photo-pricing/', calculate_passport_photo_pricing, name='calculate_passport_photo_pricing'),
    path('calculate-a4-print-pricing/', calculate_a4_print_pricing, name='calculate_a4_print_pricing'),
    path('calculate-golden-emboss-pricing/', calculate_golden_emboss_pricing, name='calculate_golden_emboss_pricing'),
    # Razorpay payment endpoints
    path('payments/create-order/', create_razorpay_order, name='create_razorpay_order'),
    path('payments/verify/', verify_razorpay_payment, name='verify_razorpay_payment'),
    # Google Drive integration endpoints
    path('drive/oauth/start/', views.drive_oauth_start, name='drive_oauth_start'),
    path('drive/oauth/callback/', views.drive_oauth_callback, name='drive_oauth_callback'),
    path('drive/list/', views.drive_list_files, name='drive_list_files'),
    path('drive/download/', views.drive_download_file, name='drive_download_file'),
]

urlpatterns += [
    path('update-vendor-service-availability/', update_vendor_service_availability, name='update_vendor_service_availability'),
    path('get-vendor-service-availability/', get_vendor_service_availability, name='get_vendor_service_availability'),
    path('update-vendor-availability/', update_vendor_availability, name='update_vendor_availability'),
    path('update-vendor-profile/', update_vendor_profile, name='update_vendor_profile'),
    path('get-vendor-profile-image/', get_vendor_profile_image, name='get_vendor_profile_image'),
    path('test-profile-image-url/', test_profile_image_url, name='test_profile_image_url'),
    path('test-r2-url-generation/', test_r2_url_generation, name='test_r2_url_generation'),
    path('test-r2-simple/', test_r2_simple, name='test_r2_simple'),
    path('list-vendor-folder/', list_vendor_folder, name='list_vendor_folder'),
    # New job management endpoints
    path('accept-job/', views.accept_job, name='accept_job'),
    path('mark-job-completed/', views.mark_job_completed, name='mark_job_completed'),
    path('retry-failed-job/', views.retry_failed_job, name='retry_failed_job'),
    path('cancel-failed-job/', views.cancel_failed_job, name='cancel_failed_job'),
    # Notification endpoints
    path('get-user-notifications/', views.get_user_notifications, name='get_user_notifications'),
    # Accept print job endpoints
    path('accept-print-job/', views.accept_print_job, name='accept_print_job'),
    path('mark-job-completed/', views.mark_job_completed, name='mark_job_completed'),
    path('hide-completed-job/', views.hide_completed_job, name='hide_completed_job'),
    path('debug-file-locations/', views.debug_file_locations, name='debug_file_locations'),
    # Connection monitoring endpoints
    path('vendor-connection-heartbeat/', views.vendor_connection_heartbeat, name='vendor_connection_heartbeat'),
    path('get-vendor-connection-status/', views.get_vendor_connection_status, name='get_vendor_connection_status'),
]