# Generated by Django 5.2.3 on 2025-06-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrintJob',
        ),
    ]
