# Generated by Django 5.2.3 on 2025-07-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
