# Generated by Django 5.0.8 on 2025-11-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorDashboardReset',
        ),
        migrations.DeleteModel(
            name='VendorReport',
        ),
    ]
